#!/usr/bin/env bash
#SBATCH --job-name=glm5-server
#SBATCH --time=24:00:00
#SBATCH --gres=gpu:l40s:4
#SBATCH --cpus-per-task=96
#SBATCH --mem=512G
#SBATCH --output=logs/glm5-%j.out
#SBATCH --error=logs/glm5-%j.err
#
# slurm-batch.sh — Submit a batch job that runs the full inference stack.
#
# Usage:
#   mkdir -p logs
#   sbatch scripts/slurm-batch.sh
#
# The job will:
#   1. Enter the Nix devShell
#   2. Start Tailscale (userspace)
#   3. Start llama-server
#   4. Run until the job time limit expires
#
# Monitor with:
#   tail -f logs/glm5-<jobid>.out
#   squeue -u $USER
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_DIR"

echo "=== GLM-5 Batch Job ==="
echo "Job ID:   $SLURM_JOB_ID"
echo "Node:     $(hostname)"
echo "Started:  $(date -Iseconds)"
echo ""

# Create log directory
mkdir -p "$PROJECT_DIR/logs"

# Source GPU passthrough for nixsa if needed
if [ -f "$PROJECT_DIR/nixsa-gpu-setup.sh" ]; then
  source "$PROJECT_DIR/nixsa-gpu-setup.sh"
fi

# Load environment
if [ -f "$PROJECT_DIR/.env" ]; then
  set -a; source "$PROJECT_DIR/.env"; set +a
fi

# GPU info
echo "GPUs:"
nvidia-smi --query-gpu=index,name,memory.total --format=csv,noheader 2>/dev/null || echo "  (nvidia-smi unavailable)"
echo ""

# Cleanup handler — stop Tailscale on job exit
cleanup() {
  echo ""
  echo "=== Shutting down ($(date -Iseconds)) ==="
  # Use nix run so we get the right PATH
  nix run .#tailscale-down 2>/dev/null || true
  echo "Done."
}
trap cleanup EXIT INT TERM

# Run everything inside the nix devShell
nix develop --command bash -c '
  # Start Tailscale
  glm5-tailscale-up

  # Write connection info to a file other processes can read
  TS_IP=$(tailscale --socket="$TS_SOCKET" ip -4 2>/dev/null || echo "unknown")
  cat > "$PROJECT_DIR/.connection-info" <<EOF
# Generated by SLURM job $SLURM_JOB_ID on $(date -Iseconds)
# This file is auto-generated — do not edit.
SLURM_JOB_ID=$SLURM_JOB_ID
NODE=$(hostname)
TS_IP=$TS_IP
TS_HOSTNAME=${TS_HOSTNAME:-hpc-glm5}
PORT=${PORT:-8080}
API_URL=http://$TS_IP:${PORT:-8080}/v1
HEALTH_URL=http://$TS_IP:${PORT:-8080}/health
EOF

  echo ""
  echo "Connection info written to .connection-info"
  echo ""

  # Start the server (blocks until killed)
  glm5-serve
'
